# Generated by Django 4.1.5 on 2023-12-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('hora_inscripcion', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'RESERVADO'), ('COMPLETADA', 'COMPLETADA'), ('ANULADA', 'ANULADA'), ('NO ASISTENTE', 'NO ASISTENTE')], max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_FINAL.instituciones')),
            ],
        ),
    ]
